// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvZaKCj4zILZogQ0yy2_DBPMv4QCgTzwo',
    appId: '1:1092602569915:android:64440326b23c3919e1359e',
    messagingSenderId: '1092602569915',
    projectId: 'and20roid-a7e09',
    storageBucket: 'and20roid-a7e09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXX8sFu37-z7vD4CTJfCXDpqn6b9pyErg',
    appId: '1:1092602569915:ios:0ed1151ada49439ee1359e',
    messagingSenderId: '1092602569915',
    projectId: 'and20roid-a7e09',
    storageBucket: 'and20roid-a7e09.appspot.com',
    androidClientId: '1092602569915-57cunsmh1d0ioi9h8033nf0l25ijapf7.apps.googleusercontent.com',
    iosClientId: '1092602569915-t2kimo16rkljqbmrtqsf55m3fv110c3s.apps.googleusercontent.com',
    iosBundleId: 'com.codekunst.and20roid',
  );
}
